services:
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/controllers/:/app/backend/controllers/
      - ./backend/public/:/app/backend/public/
      - ./backend/routes/:/app/backend/routes/
      - ./backend/server.js:/app/backend/server.js
    ports:
      - "${API_PORT}:8080"
    environment:
      - NODE_ENV=development
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - DATABASE_URI=${DATABASE_URI}
      - PORT=${API_PORT}
      - WEB_URL=${WEB_URL}

  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src/:/app/frontend/src/
      - ./frontend/public/:/app/frontend/public/
      - ./frontend/tailwind.config.js:/app/frontend/tailwind.config.js
    ports:
      - "${VITE_WEB_PORT}:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL}
      - VITE_WEB_PORT=${VITE_WEB_PORT}
      - VITE_MAPBOX_ACCESS_TOKEN=${VITE_MAPBOX_ACCESS_TOKEN}
    depends_on:
      - backend-dev
    
  backend-prod:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "${API_PORT}:8080"
    environment:
      - NODE_ENV=production
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - DATABASE_URI=${DATABASE_URI}
      - PORT=${API_PORT}
      - WEB_URL=${WEB_URL}
  
  frontend-prod:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "${VITE_WEB_PORT}:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_WEB_PORT=${VITE_WEB_PORT}
      - VITE_MAPBOX_ACCESS_TOKEN=${VITE_MAPBOX_ACCESS_TOKEN}
    depends_on:
      - backend-prod