name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create root .env file from secrets
        run: |
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env
          echo "WEB_PORT=${{ secrets.WEB_PORT }}" >> .env
      
      - name: Create backend .env file from secrets
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> backend/.env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> backend/.env
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> .env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
          echo "BUCKET_REGION=${{ secrets.BUCKET_REGION }}" >> .env
          echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> .env
          echo "SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}" >> .env
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env
          echo "WEB_URL=${{ secrets.WEB_URL }}" >> .env
      
      - name: Create frontend .env file from secrets
        run: |
          echo "MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}" >> frontend/.env
          echo "API_URL=${{ secrets.API_URL }}" >> frontend/.env

      - name: Build and push frontend and backend images
        run: |
          docker compose build backend-prod frontend-prod
          docker tag rideshare-backend-prod jschur/rideshare-backend:latest
          docker tag rideshare-frontend-prod jschur/rideshare-frontend:latest
          docker push jschur/rideshare-backend:latest
          docker push jschur/rideshare-frontend:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker images
        run: |
          docker pull jschur/rideshare-backend:latest
          docker pull jschur/rideshare-frontend:latest

      - name: Remove old containers
        run: docker-compose down

      - name: Run docker-compose up
        run: docker-compose up -d